name: image_magick_ffi
description: Dart bindings for ImageMagick C library which is used to edit images.
version: 0.0.1-dev.9
homepage: https://github.com/Haidar0096/image_magick_ffi
repository: https://github.com/Haidar0096/image_magick_ffi
documentation: https://github.com/Haidar0096/image_magick_ffi

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=2.11.0"

dependencies:
  plugin_platform_interface: ^2.0.2
  ffi: ^2.0.1

dev_dependencies:
  ffigen: ^7.2.0
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
        dartPluginClass: ImageMagickFFIPlugin
      windows:
        ffiPlugin: true
        dartPluginClass: ImageMagickFFIPlugin